sandstorm-io/sandstorm-website

apps/index.html
Sandstorm provides a local.sandstorm.io domain so that there is
a domain that provides TXT records for people running the Sandstorm
code on their own machine in a sort of development capacity.
Meanwhile, the /apps/ list contains (before this patch) the plain
localhost name, which if clicked-on, will lead to the message:
```Error looking up DNS TXT records for host localhost: queryTxt ENOTFOUND
```
in the browser.
This patch uses local.sandstorm.io instead.
=> Adjust /apps/ to point at quasi-localhost

apps/index.html
We temporary moved the git repository from github to a self-hosted gitlab instance, while we work on a new UI for the next release.
Grain update was tested and is working as expected (we have some data migrations).
Note that this PR should be merged quickly because we're about to delete the previous sandstorm package hosted on github.
=> Upgrade LibreBoard to v0.8.0

apps/index.html
Uses the `Content-Encoding` header fix from https://github.com/sandstorm-io/sandstorm/pull/229.
=> GitWeb version 1

apps/index.html
MediaWiki app was missing the start of it's `<div>`.
JGraph is draw.io's developer, not a maintainer.
=> Miscellaneous fixes

apps/index.html
Notable things about this changeset:
* It uses Debian-style package filenames -- specifically, this came
from Meteor 1.0.3.1, and this is the first release by me.
* It has a new app ID. There have been a large number of
backwards-incompatible changes between the previous Meteor todo demo
app and this one, and @kentonv and I decided that it was better if
we avoided stomping on people's data, and it didn't seem necessary
to migrate it since this is just a toy app.
=> Add refreshed Meteor Todos port

apps/index.html
Includes "developer" and "guest" roles. The "developer" role is default, as it corresponds to the permissions that sharing-by-URL used to grant.
=> GitWeb v0.0.3

apps/index.html
I'll want to upgrade the shared Acronymy instance to the new sharing model at some point. That'll be easiest if I just have to edit the redirect I've set up at https://dwrensha.ws/acronymy .
=> Link to Acronymy instance from a domain I control.

install/index.html, install/install.css, install/install.js
**Goal**
This pull request creates an `/install/` page, so that when people know they need to install Sandstorm, they can go to a page that is more inviting than github.com/sandstorm-io/sandstorm.
I worked with @neynah on the colors and spacing.
I'm interested in this primarily so that users of `demo.sandstorm.io` can see a button at the top that links to this page. See https://github.com/sandstorm-io/sandstorm/pull/408 for the Sandstorm shell side of things.
**Status**
Ready for review/merge.
This pull request must go live before https://github.com/sandstorm-io/sandstorm/pull/408 .
**Technical details**
Features:
* If you visit this page with #EtherCalc   tells you Sandstorm
is the easiest way to run EtherCalc. The purpose of this
is to integrate with a link at the top of the demo.
* …
=> Create version 1 of install page

install/index.html
This is necessary so we can get a sense of _which_ install pages
are being seen by visitors to the site.
Testing done:
* Manually test that `fullUrl` is the full URL, including the hash, by temporarily adding an `alert(fullUrl);` line. (I've removed that line before submitting this pull request.)
=> Record full URL in analytics, including hash

index.html
Linking straight to Github is less helpful than our own page that is meant to
guide people through the install process.
=> Make "Run your own" link point to the /install/ page

install/index.html
Per https://developers.google.com/analytics/devguides/collection/analyticsjs/pages ,
the "pageview" event needs only the path; it figures out the domain and
protocol by itself.
Therefore, we are cluttering up GA with bad data at the moment until we deploy
this.
Requesting @kentonv 's review + merge.
=> Use just path + hash for Google Analytics

apps/index.html
This is the only thing preventing the Sandstorm demo from working in IE9.
See http://caniuse.com/#feat=dataset
=> IE9 compat: avoid using dataset property directly, prefer getAttribute

apps/index.html
The 'porting guide' link was outdated. It pointed through two manual redirects to the packaging guide.
This changes it to point directly to the guide.
=> Update link to packaging guide.

apps/index.html
The copy/paste offer template instructions now automatically configure the "store" credential helper.
This depends on https://github.com/sandstorm-io/sandstorm/pull/633, so should not be merged until that fix makes it onto the Alpha and Oasis servers.
=> Gitweb version 5.

apps/index.html
http://y.hyperbotics.org/ now points to https://github.com/harshavardhana/y, and https://github.com/hyperbotics/y is gone.
=> Update link for Game of Y.

index.html, install/index.html, style.css
See commit log messages for these 4 commits for details.
Props to @xcombelle for noticing that the main site needs proper links to the docs.
=> Link to docs from front page & install page. Use install page more consistently.

style.scss
Small adjustment based on user testing results. User was initially confused and thought there were 3 options: Managed Hosting, Sandstorm Oasis, and Self-host.
We may also want to consider changing "Sandstorm Oasis: Hosting by Sandstorm.io" to something like "Hosting by Sandstorm.io on Oasis" so it looks even less like a 3rd option?
=> Font weight adjustment on /get

style.scss
Also added padding below self-host plans so that they don't look attached to each other when they're stacked.
=> Mobile padding tweaks

Gemfile, Gemfile.lock, README.md, _config.yml
Rationale: I really do not want to run gem install as root. This also switches
the list of gems to "executable documentation", which ensures they do not get
out of sync with reality.
=> Switch to bundler

Guardfile
This avoids a crash in match() in the "listen" gem.
=> Guardfile: Use all regexes, all the time

business.html, get.html
This commit adds pricing to the Sandstorm for Work page. See also this docs pull request:
- https://github.com/sandstorm-io/sandstorm/pull/1659
This adds a link to the `#special-pricing` div within the docs. The purpose is to help non-profits discover that there is special pricing available in a way that helps for-profits still believe Sandstorm for Work is a worthwhile way to spend money.
Screenshot attached. I experimented with a few other places to add pricing. I think this is the most time-effective thing we can do. I think that most other places require more significant redesigns. For example, we could create a new icon box for this pricing information, but I think that draws more attention to it than needed, and would take some design work.
=> Add pricing to Sandstorm for Work page

_layouts/page.html, _posts/2016-01-22-8-new-open-source-apps.md, _posts/2016-06-13-photo-library-lychee.md, _posts/2016-08-31-sandstorm-for-work-ready.md, business.html, developer.html, features.html, get.html, images/check-dark.svg, images/check.svg, images/get-oasis.svg, images/get-organizations.svg, images/get-self-host.svg, images/xmark.svg, index.html, style.scss
Addresses #221 
Changes in this commit:
- added simplified feature comparisons; emphasized hosting, administering, and support
- added graphic for Sandstorm on Oasis
- added check & x-marks
- added tagline: "Run Sandstorm anywhere." (Open to suggestions) 
- removed Oasis section
- consolidated Oasis plans into one of the 3 product options
- changed description copy for each of the products
- changed Standard to Sandstorm Standard
- changed bottom "Questions?" call to action to "Let us help you get the most out of Sandstorm"
- colour-themed each of the products (bg colour and buttons)
- change /business so that "Core and Security" will say "Sandstorm Standard" and "Business" will say "Sandstorm for Work".
Note: I recognize that "Sandstorm for Enterprise" will be under "Sandstorm for Work" …
=> Feature comparison

get.html, style.scss
Copy is ready for review; styling still needs some work.
In this PR:
- added a "See Pricing" button that displays a popup when clicked
- added a popup that displays the Oasis pricing table
Remaining to dos:
Not in this PR:
- I think we should also communicate the benefits of using Oasis on this popup but I'll create a separate PR for that so as to not block this PR.
=> Re-add Oasis pricing table

go/education.html, style.scss
Still waiting for more feedback but I'll submit these changes for now. As soon as this gets merged & deployed I'll share it with more educators. :)
Changes in this PR:
- Changed the emphasis from installing Sandstorm to using Sandstorm in "Why use Sandstorm" sub header text
- App market link is a button now; also more app market links in general
- Changed sub header text for "Here's why IT teams love it" to focus more on what IT teams gain rather than repeating what instructors & students gain
- Changed bottom call-to-action "Start Sandstorm setup" text to "Start free trial"
- Other minor tweaks to copy (e.g. "the" -> "your")
After screenshot:
Before screenshot:
=> Education landing page copy changes

_includes/stats-support.js, _includes/stats.html, _layouts/page.html, stats.js
We inline the script needed to support this in the page `<head>` so we
can generate stylesheets according to experiment membership *before*
any page content is displayed.  Otherwise, we'd potentially wind up
with flash of unstyled content or page reflow, which is undesirable.
As a result of the above inlining of all the early script, stats.js is no
longer used directly by this site, but remains as a publicly-consumable
endpoint for use by other sites that src it.  This change also exposes
the experiment set (including membership), which should allow us to
maintain a single copy of experiment rules/membership sets that will
be used by all of our properties.
This change does not actually enable any experiments; they will come
in future changes.
=> Add experiments framework

_layouts/page.html
Also moved "Documentation" section so that it comes before "How it Works". Documentation information should be more accessible & visible.
It might be worthwhile to add any additional relevant links under "Documentation".
=> Added App Market and Education links to footer

_includes/stats-support.js
0x1999999 is much less than 0x19999999, but looks almost the same.
Hilariously, the example case has the appropriate number, but the actual
experiment definition lost a digit somewhere.  This resulted in ~1/16th
the expected number of users in the experimental condition as expected,
which means that we have very little experimental data.
*grumble* this sort of thing is exactly why I wanted this field to be a
membership fraction, not a large integer...
=> Fix typo that resulted in too few users in experimental condition

install.html, style.scss
Perhaps we should add a string to provide more clarity? What are your thoughts on the copy @paulproteus?
White on the tangerine background might be a bit hard to see; it does match the AWS colours though. I might just style it as a regular button but have some AWS-styled image above.
=> AWS button

style.scss
Not sure if this was intentional but it looks weird to me.
Before:
After:
=> Don't show a double-border around the Basic plan.

_includes/stats.html, ga-helper.js, get.html, install.html
I manually tested with the GA Debug tool that this retains the old behavior on /install and that the GA debug tool shows the right behavior on /get.
=> Add link stats recording to /get

style.scss
Apparently given an inline style of width: 100% and a max-width: 1200px CSS
rule, the max-width rule wins.
=> Fix where the stripe overlay doesn't cover the whole screen

apps/index.html, apps/style.css, cla/corporate.html, cla/index.html, cla/individual.html, cla/style.css
This updates the CLA and old app list to use Source Sans instead of Open Sans, and removes the Google Fonts dependency from both.
Tried to use `../fonts/sourcesans.css` on my local, it didn't work. In particular, it seemed to correctly identify the CSS file, and attach it, but it didn't seem to find the fonts, as it used Arial. However, it did work when I explicitly specified the CSS file's location.
=> Switch to Sandstorm-hosted Source Sans

_posts/2019-09-15-shutting-down-oasis.md, get.html, style.scss
Sorry @ocdtrekkie... you were right about the motivation for mass transfer. :/
But honestly, I looked at it, and running a self-hosted server on Digital Ocean these days is pretty much strictly superior to Oasis, and self-hosting was always the whole point of Sandstorm... so it seems wrong for people to keep their data on a service that has a bus factor of 1.
=> Announce shutdown of Sandstorm Oasis at end of year.

install.html
Fixes https://github.com/sandstorm-io/sandstorm/issues/3154
Asheesh added this originally, unless he has what he did, we'd have to recreate it. I am not sure if we recreated it using a third party embed is our best choice here anyways. I propose we just drop this for now.
=> Remove embed for non-existent demo video

install.html
Pointed out by slezyr on the HN thread.
=> Remove Oasis "alternative" from the install page

_posts/2020-02-22-announcing-vagrant-spk-1.0.md
I wrote a blog post for the 1.0 release of vagrant-spk. I think it's worthwhile to let people know we're updating app packaging tools actively, and major changes like the port change and enter-grain working right are noteworthy.
I future-dated this for next weekend, since I barely managed to get vagrant-spk 1.0 packed by late Sunday night.
=> Announce vagrant-spk 1.0 to the world

feed.xml
Fixes #326. I haven't tested this yet (I've not tried building the Sandstorm website before), but as long as the author information listed at the top of posts is available to what builds this feed, I assume this should work?
I did some research, because I want to use the information already provided in our posts, which doesn't include email addresses. I looked at a bunch of RSS feeds I follow, and noticed that very few actually use the optional field `<author>`, which requires an email address be provided. Many use `<dc:creator>`, which is less strict, see https://www.rssboard.org/rss-profile#namespace-elements-dublin-creator
=> Add author name to RSS feed

business.html, style.scss
Blackrock isn't really maintained, so this is a little misleading.
See also discussion at
https://github.com/sandstorm-io/blackrock/issues/48#issuecomment-671601610
=> Remove references to blackrock on /business.

_posts/2020-02-03-reviving-sandstorm.md, _posts/2020-08-08-tiny-tiny-rss-and-the-powerbox.md, community.html
So, as things have escalated, note that Whitequark has stopped servicing Freenode, which places us in a bit of a "if a tree falls in the forest and nobody can hear it, does it make a sound" problem. This is the PR to redirect new people to join us on Libera instead, where we are registered and Whitequark is logging us.
Some additional thoughts:
- I've left KiwiIRC as the web client for now, but we may need to change this in the near future, as it's owner has abandoned all things IRC. They said they intend to hand it off at some point, but who to, who knows.
- A lot of our blog posts include mention of our IRC. Should we consider those historical and leave them, or should we update them to ensure nobody reading about us ends up in the wrong place? I think updating them on the blog is …
=> Update community page with new IRC links

_layouts/page.html
This reverts commit 7e8a2fd5e4c27d796fbc495168e2c42d6729f9d8.
The rest of the website is no longer pitching to business intranet use cases, so this shouldn't either.
=> Remove "behind the firewall" in og:description / social media preview.

community.html, style.scss
LinkedIn is kinda irrelevant here, and our Meetup presence has long since gone away (the URL just loads the Meetup home page). I think we should simply drop both. Looking at Facebook, and the messages that have been sent at it in the past couple years... we might want to keep that open, I think, but I don't know. Fixes #336.
Going to play with the centering too, Cloudflare Pages makes this fun I think?
=> Community: Remove LinkedIn and Meetup

_layouts/page.html
In #328, Ian deleted the scale-out section of the business page, so we definitely don't need a footer link to it.
=> Remove footer link to deleted section

install.html
I think this fixes #346 adequately, though I am unhappy with the destination. The FAQ link here would've told @jdougan about the memory issues, but we have a *different* page which does not, for troubleshooting a new install! We probably should rework what is between these two pages.
=> Add help to top of install

_includes/sidebar.html, _layouts/page.html, community.html, style.scss
This removes Facebook from the community page, as well as the footer and sidebar on every page.
I did leave this message on the page, though since it isn't from the page itself, it's on the "Community" tab of the page, as opposed to the front page. It does appear above any other user-submitted posts to the page though, so hopefully people considering posting there will see it.
=> Remove links to Facebook

apps/index.html
I enjoy that this page still exists, and includes ancient Sandstorm apps that still work. However, I feel like we should probably update the top of the page to specify where the current app site is, in case someone somehow manages to get here accidentally. I also deleted Oasis from it.
=> Old apps page is no longer a placeholder

_layouts/page.html
We just made an official mastodon account for the project; this patch adds the metadata link to "verify" the account.
Separately we should add it to the community page, but that requires mucking with fetching a logo and such, so I figured I'd go ahead with just this.
=> Add link rel="me" for mastodon account.
