apps/index.html
apps/style.css

Missing line break in IPython listing was quirky. And we had some amp;s and some ands and an amp; with no spaces around it. The inconsistency made me sad.
And while I doubt I'll update Blocks further unless I need to update compatibility with the platform, as it's pretty complete, I like having dates and versions, and now that other apps have it, I am adding my details.

List fixes and Blocks info

---

apps/index.html

See the commit log message for the two commits for further details.
I've tested a few of these randomly, and they seem to work fine.
One thing I noticed in my testing is that it was important to test against a local install that didn't have the packages installed! Otherwise I wasn't testing that the URL is being passed through properly.

Data attribs for app list

---

apps/index.html

Includes new "Playlists" and "Chats" tabs, with autologin.

Groove Basin version 3

---

apps/index.html

Lots of fixes and speedups. Can now handle `Content-Encoding: gzip` on requests, due to https://github.com/sandstorm-io/sandstorm/pull/229.

GitLab version 1

---

apps/index.html

Also fix up text that refers to Mailpile still being an alpha.

Bump Mailpile to v5 (removes some buttons that don't make sense)

---

apps/index.html

Addresses https://github.com/dwrensha/sharelatex/issues/1.

ShareLaTeX version 6, with cyrillic alphabet support

---

apps/index.html

https://github.com/jacksingleton/hacker-slides
A simple app that combines Ace Editor and RevealJS. You can write markdown on the left, and preview your presentation on the right.
I put this together pretty quickly because I could not find an open source web based presentation app. It still needs some work, but is functional!
Let me know if you have any feedback.

Add HackerSlides

---

apps/index.html

Update ghost to v9

---

apps/index.html

This is a bugfix that fixes notes that used complicated markdown from
rendering

Update Laverna to v5

---

apps/index.html

Fixes https://github.com/sandstorm-io/sandstorm/issues/292

Handle demo correctly, and change buttons to "Try Demo" when appropriate

---

apps/index.html

Update Hacker Slides to fix some bugs: https://github.com/jacksingleton/hacker-slides/issues?q=is%3Aissue+milestone%3A0.1.1

Update Hacker Slides

---

apps/index.html

Now "contributor" is the default role.

Groove Basin v0.0.5

---

apps/index.html

No longer pegs your CPU!
https://github.com/andrewrk/groovebasin/issues/319

Groove Basin v0.0.6

---

apps/index.html

This version adds a read-only "viewer" sharing permission, features a revamped icon set, among various other improvements.

EtherCalc 2015.05.18.3

---

apps/index.html

Added support for X-Sandstorm-Username and multiple stickers on cards from master.

Update Scrumblr to 0.3

---

apps/index.html

As the title says
cc: @paulproteus

Add GitWeb Pages to the app list

---

preorder.html

Declare that billing starts by August

---

index.html

* Remove clutter above the fold.
* Emphasize that it runs on Linux (so people know what self-install would be like)
* Remove unnecessary words below the fold

Simplify top text

---

install/index.html

Also list the RAM requirement.
Hopefully resolves user confusion that resulted in https://github.com/sandstorm-io/sandstorm/issues/539 (cc: @ocdtrekkie @StuartRus)

Explain that we require 64-bit Linux

---

apps/index.html

Reverts sandstorm-io/sandstorm-website#87
Doesn't work.

Revert "Update Let's Chat to v5 (0.4.1 upstream)"

---

apps/index.html

Fixes error message for non-logged in users.

Update Let's chat to v6

---

apps/index.html

Update gitweb to version 4.

---

apps/index.html

Reverts sandstorm-io/sandstorm-website#90
still broken

Revert "Update Let's chat to v6"

---

apps/index.html

This fixes certain usernames causing login problems.
Specifically, duplicate usernames were no longer handled correctly, and
names with non alphanumeric characters were causing problems.

Update Let's Chat to v7

---

apps/index.html

Fixes theme/plugin upload on Oasis: https://github.com/dwrensha/wordpress-sandstorm/issues/5

Update WordPress to version 5.

---

index.html

I only made the change on the home page. I wonder if the `apps/index.html` file is still in use in some cases and if I should update it.

Acknowledge LibreBoard rename into Wekan

---

index.html

I believe that imperative verbs are better calls-to-action than questions,
so I adjusted the text here. This is a small change, but I hope it is a
good one.
This came out of a lunchtime brainstorming session that @zarvox and @paulproteus had.
Action requested:
- Please review and either merge/close. No hard feelings either way; it's from a brainstorm session.

Make call-to-action juicier

---

_posts/2016-01-11-website.md

Be more accurate and inclusive

---

style.scss

- shrunk social media icons
- enlarged post title text
- adjusted padding

Blog style tweaks

---

how-it-works.md

It's small, it's inconsequential. I mentioned it in IRC, but you guys were probably busy on bigger things.

Match case of apps' branding

---

community.html
how-it-works.md
index.html

Fix capitalization of trademarks/brands

---

features.html

Fix typo on features page: loud to cloud
BR,
xet7

Fix typo on features page: loud to cloud

---

how-it-works.md

While reading this page on the website I got distracted by a few too many misspellings. I haven't checked the other pages. (I used to do more copyediting for erights.org, though I don't have time these days.)

Correct misspellings and typos.

---

about.html
images/home-banner.svg
index.html
style.scss

Buttons are now easier to see and I think the try button text is now less confusing.

Increased button contrast on home page, also "Try a Quick Demo"

---

_includes/sidebar.html
style.scss

Added recommended posts to sidebar

---

install.html

/install: Mention installer docs & sandcats

---

_posts/2016-02-29-security-track-record.md

@kentonv requesting your merge/review.
- Note: I added a new section to the end to (attempt to) hammer home the message. Maybe you're +1 or -1 on that section. I do plan to add it to the Mailchimp newsletter version of this, too, fwiw.

Add blog post about security track record

---

go/security.html

Fixed wording

---

go/security.html
style.scss

@neynah I wrote text but don't have any ideas about graphics / formatting. Thoughts?

Add section to security landing page about inhouse networks.

---

go/security.html

Changed form links

---

business.html
get.html

Thanks @neynah for feedback. See screenshots on #project-adminpanel in Rocket.Chat. (Hmm. We should make a Rocket.Chat the community can read.)

Slight revisions to pricing formatting

---

business.html
get.html
go/security.html

@paulproteus @neynah I've made the button text be "Start a Free Trial". Does that seem OK?

Change all 'early access' links to '/get-feature-key'.

---

_layouts/page.html
developer.html

@paulproteus I hope it's OK that I went ahead and revised your commit: #174

Rename Developer Docs to Developer Hub

---

_posts/2016-05-16-designing-open-source.md

Hoping to get this published for Monday! :)

Blog post for May 16

---

_posts/2016-05-23-case-study-journalists

Ready to be published for Monday morning.

May 23rd blog post

---

_posts/2016-05-31-whats-new.md

@kentonv I've tested this locally and happy to see it merged & go live whenever you can.

Add whats-new-in-may post

---

_posts/2016-06-20-drew-object-capabilities.md

I hope you don't mind merging this. This video took a little longer to render but the quality is so much better than the other one. I've also figured out a more streamlined process for editing & uploading the videos so things will be smoother next time. :)

Link to higher quality video

---

_posts/2016-02-05-app-author-publicity-oasis.md

@kentonv requesting your review/merge.
@zomebiezen I believe this addresses the question you had about how to redeem this credit. Let me know if you agree.

Explain how to redeem app author credit

---

index.html

Requesting review from @kentonv. I suspect there will be many changes! :)
Images & style changes will come in separate commits. Addresses #204

Productivity suite copy changes

---

get.html
style.scss

Ready for review.
- I think it would look better if the pricing section in the left "Standard" plan were vertically aligned in the centre but I can fix that later.

Sandstorm for Work introductory offer

---

_includes/sidebar.html
_posts/2016-08-31-sandstorm-for-work-ready.md

Also added the decentralization/diversity post to sidebar.

Sandstorm for Work out-of-beta blog post

---

_includes/sidebar.html
style.scss

Refs https://github.com/sandstorm-io/sandstorm/issues/2545

Say it is a productivity suite

---

_posts/2016-09-13-whats-new.md

This is a test commit to verify that I can update the website.

Temporarily change - to :

---

get.html

This JS makes sure that:
- Clicking the (X) icon in the corner of the modal makes it go
away without navigating the page, if the page was first-visited
while not looking at the modal. (Requested by @kentonv)
- Clicking the background will dismiss the modal, too. (Requested
by @neynah + @paulproteus.)

Oasis pricing table: Add more JS

---

install.html

Close #248 
Can't merge this until the new install.sh is the default, though.

Claim it runs on 3.10

---

stats.js

Explicitly export a method named sandstormTrackView
This will make it easier to use in react/other environments that don't actually do a page load on navigation.

Wrap the stats code in an anonymous function

---

_posts/2016-11-10-rhel-centos-arch-support.md

Probably should have posted this two weeks ago. Oops.

Blog post about RHEL etc. support.

---

_includes/stats-support.js
_includes/stats.html
_layouts/page.html
stats.js

This builds on #257, so merge that first.

Add trackClick method for stats

---

_includes/stats-support.js
install.html
style.scss

Extends #257 and #259, so merge those first.

/install experiments: track clicks, add autoplay screencast experiment

---

install.html

Testing done:
- I installed the Google Analytics Debugger extension for Chrome and made sure that the
event fires.

Store data on if people click the AWS install link

---

get.html
style.scss

Added phone number to /get

---

get.html
style.scss

- added bg image
- adjusted padding
- removed </li>
Now:
Before:

Tweaked styling on number section on /get

---

_layouts/page.html
style.scss

Close #274
Also perform some trivial whitespace adjustments that my editor really wanted
to perform.

Simplify top bar

---

index.html

Remove full-width mailing list signup bar from front page

---

_layouts/page.html
get.html
style.scss

For @zarvox! 
Below nav on every page:
Above footer on every page:
Mobile:

Add donation bar below nav and above footer

---

_includes/stats-support.js
_layouts/page.html
style.scss

Sits atop #277.  Requires that sandstorm-io/prod#12 go live before merge/deploy.

Donations backend integration

---

images/help-discuss.svg
images/help-share.svg
images/help-talk.svg

Update vector illustrations on /community

---

community.html

Changes:
- copy improvements
- added a few links (including one to CONTRIBUTING.MD)
- removed `target="blank"`s
- adjusted some indenting
- removed unnecessary !s

Improve copy on /community

---

_layouts/page.html
style.scss

Footer text margin and letter case tweaks

---

install.html

We're no longer at the point that it is important to suggest a specific LTS release, I think.
Closes #192

Recommend Ubuntu LTS

---

_includes/sidebar.html
_layouts/page.html
community.html

Remove Google+ buttons

---

index.html

Just a quick fix mentioned by https://github.com/sandstorm-io/sandstorm/issues/3340

Remove comment about our community-run servers

---

Gemfile.lock
_posts/2020-08-04-tiny-tiny-rss-and-the-powerbox.md
_posts/2020-08-08-tiny-tiny-rss-and-the-powerbox.md

This is still WIP; among other things it ends way too suddenly; need to put in a conclusion or something. Marking it as a draft PR, but feedback welcome. (I'll obviously need to bump the date to whenever we actually merge this).

TTRSS update blog post.

---

features.html

This was reported on the mailing list:
https://groups.google.com/forum/#!topic/sandstorm-dev/E8TM1vdW-Co

Grammar fix.

---

_posts/2021-06-17-sandstorm-community-fundraising.md

This is a first draft of a blog post promoting the FundOSS drive and the community opencollective more broadly. I'm sure it could use some work. Thanks to @garrison for prodding us on this.
cc: @ocdtrekkie, @kentonv

New blog post re: FundOSS & OpenCollective

---

404.html

Cloudflare Pages needs this, otherwise it just serves the home page on 404.

Add a dumb 404 page.

---

_layouts/page.html
_posts/2024-01-14-move-to-sandstorm-org.md
style.scss

Sorry, I should have done this a while ago...

Add banner and blog post about the move to sandstorm.org.
